export const pg_data_type: { [key: string]: string } = {
    "bigint"			: "bigint",
    "bigserial"			: "bigint",
    "bit"				: "string",
    "bit varying"		: "string",
    "boolean"			: "boolean",
    "box"				: "string",
    "bytea"				: "string",
    "character"			: "string",
    "character varying"	: "string",
    "cidr"				: "string",
    "circle"			: "string",
    "date"				: "Date",
    "double precision" 	: "number",
    "inet"				: "string",
    "integer"			: "number",
    "interval"			: "string",
    "json"				: "object",
    "jsonb"				: "object",
    "line"				: "string",
    "lseg"				: "string",
    "macaddr"			: "string",
    "macaddr8"			: "string",
    "money"				: "",
    "numeric"			: "number",
    "path"				: "string",
    "pg_lsn"			: "string",
    "pg_snapshot"		: "string",
    "point"				: "string",
    "polygon"			: "string",
    "real"				: "number",
    "smallint"			: "number",
    "smallserial"		: "number",
    "serial"			: "number",
    "text"				: "string",
    "time"				: "",
    "timestamp"			: "",
    "tsquery"			: "string",
    "tsvector"			: "string",
    "txid_snapshot"		: "string",
    "uuid"				: "string",
    "xml"				: "string"
}